// src/components/Risk/sampleData.js

export const SAMPLE_DATA = [
  {
    id: 5,
    severity: '긴급',
    severityLevel: 3,
    severityColor: 'error',
    timestamp: '2025.11.02 17:20:15',
    threatType: '비정상 Modbus 쓰기',
    sourceIp: '192.168.1.110',
    macAddress: 'AA:BB:CC:11:22:33',
    targetDevice: 'HMI-01',
    detectionMethod: 'DL',
    status: '확인중',
    statusValue: 'investigating',
    report: '분석중',
  },
  {
    id: 4,
    severity: '경고',
    severityLevel: 2,
    severityColor: 'warning',
    timestamp: '2025.11.02 17:16:04',
    threatType: '명령 시퀀스 이상',
    sourceIp: '192.168.1.22',
    macAddress: 'BB:CC:DD:22:33:44',
    targetDevice: 'PLC-102',
    detectionMethod: 'Rule',
    status: '신규',
    statusValue: 'new',
    report: '확인',
  },
  {
    id: 3,
    severity: '긴급',
    severityLevel: 3,
    severityColor: 'error',
    timestamp: '2025.11.02 16:45:10',
    threatType: '리플레이 공격',
    sourceIp: '192.168.1.33',
    macAddress: 'CC:DD:EE:33:44:55',
    targetDevice: 'HMI-02',
    detectionMethod: 'Rule',
    status: '신규',
    statusValue: 'new',
    report: '확인',
  },
    {
    id: 2,
    severity: '긴급',
    severityLevel: 1,
    severityColor: 'success',
    timestamp: '2025.11.02 13:20:56',
    threatType: '잘못된 기능 코드',
    sourceIp: '192.168.1.44',
    macAddress: 'DD:EE:FF:77:88:99',
    targetDevice: 'PLC-101',
    detectionMethod: 'Rule',
    status: '조치완료',
    statusValue: 'completed',
    report: '완료',
  },
    {
    id: 1,
    severity: '경고',
    severityLevel: 1,
    severityColor: 'success',
    timestamp: '2025.11.02 13:20:55',
    threatType: '잘못된 기능 코드',
    sourceIp: '192.168.1.44',
    macAddress: 'DD:EE:FF:77:88:99',
    targetDevice: 'PLC-101',
    detectionMethod: 'Rule',
    status: '조치완료',
    statusValue: 'completed',
    report: '완료',
  }
];

